### ISSUE TITLE
Modify postgres table creation job to set table id from form tag, not form name

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs-wildmeat#16]
Multiple forms can all sync to the _same_ table in Postgres. This is in the icebox, not sure if it's the right spec from the client yet. @aleksa-krolls , will check in with WCS before we proceed.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 Still pending client feedback, but it definitely will not be form `name`.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 @lakhassane confirmed that we can use form `name` to name postgres tables for now. Marking this as closed.
