### ISSUE TITLE
Allow for multiple search strings to be used

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/wcs-wildmeat#20]

**Comment by taylordowns2000** [comment]
@aleksa-krolls , multiple search strings can be provided (see below—`filters` and `filters.some(...)`) but it's unclear how we should then modify the payload from Kobo. Right now, we "tag" the form based on the filter:
```js
get('https://kf.kobotoolbox.org/api/v2/assets/?format=json', {}, state => {
  console.log(`Previous cursor: ${state.lastEnd}`);
  // Set a manual cursor if you'd like to only fetch data after a certain date
  const manualCursor = '2020-05-25T14:32:43.325+01:00';
  const filters = ['Rural Consumption', 'Préférences consommation'];
  state.data.forms = state.data.results
    .filter(resource =>
      filters.some(f => resource.name.toLowerCase().includes(f.toLowerCase()))
    )
    .map(form => {
      console.log(form.name);
      const url = form.url.split('?').join('data/?');
      return {
        formId: form.uid,
        tag: filters, // how should we tag the form?
        url,
        query: `&query={"end":{"$gte":"${manualCursor}"}}`,
        //query: `&query={"end":{"$gte":"${state.lastEnd || manualCursor}"}}`,
      };
    });
  console.log(`Forms to fetch: ${JSON.stringify(state.data.forms, null, 2)}`);
  return { ...state, filters };
});
```
I'm not a fan of the solution because "search" implies that they want to find anything that matches X, Y or Z. What happens when it matches _both_ X and Y? How should we then modify the data? In other words, you never see an interface where you Search and Replace with multiple search strings. You might find and replace, but that finding a specific string and replacing it with another.

Do you have a sense of how they want to proceed? I will push back _hard_ if they say that they want to tag a form with the "first" or "last" string that matches from the filters. That level of unpredictability is just no good.

**Comment by aleksa-krolls** [comment]
@taylordowns2000 we're well aware of the tagging recommendation, but it's not easy to implement across forms where data collection has already started. We therefore need to have a manual tagging step. Can you update this so that they can search by multiple filters (e.g., `Rural consumption`, `Préférences consommation`)... but that all forms will be assigned 1 default tag `Rural Consumption` to trigger job `02`: https://www.openfn.org/projects/1767/jobs/3603

**Comment by taylordowns2000** [comment]
Ah! Yes. That's super easy and perfectly fine from a data
integrity perspective. I had imagined that different forms would need
different tags. Implementing now.
