### ISSUE TITLE
Cannot read property '_id' of undefined error

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/wcs-wildmeat#27]
## Describe the bug
Please debug the error in the run log below. 

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/p5yaxp/runs/r89p9mn9

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/wcs-wildmeat/blob/master/jobs/2.c.market.js

### state.json
https://www.openfn.org/projects/p5yaxp/messages/m8qa64zp

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/p5yaxp/runs/r89p9mn9) and confirming success.]

**Comment by lakhassane** [comment]
@daissatou2 I corrected the issue: https://www.openfn.org/projects/p5yaxp/runs/rk585y6n
