### ISSUE TITLE
Date fields are NULL in tbl_hunter_monitoring

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/wcs-wildmeat#31]
## Describe the bug
The following date fields on`tbl_hunter_monitoring` are `NULL` when there is data in state
`date_start`
`date_end` 
`trip_start_time` 
`trip_end_time`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/p5yaxp/jobs/jvgk5e

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/wcs-wildmeat/blob/master/jobs/2.d.Offtake.js

### state.json
`Postgres DB`: See LP Wildmeat Postgres Transitional DB (WCS)
https://www.openfn.org/projects/p5yaxp/messages/061364e4-7000-79fa-9b3f-3f6e25b89f8e

## Expected behavior
The date fields in the state should match the database.

## To test/resolve
1. After the desired output is working locally (from the CLI), please [push commits to master || open a pull request].
2. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/p5yaxp/runs/06164216-ec69-7068-830a-2cd014b9cb7c) and confirming success.]

**Comment by lakhassane** [comment]
@daissatou2 I see. Do you know first why those 4 dates have different types? I would assume `date_start` and `date_end` should be the same type. as well as `trip_end_time` and `trip_start_time`
