### ISSUE TITLE
Add `await` to all findValue(...) instances 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/wcs-wildmeat#32]
## Describe the bug
Currently the job mappings are returning `{}` instead of the value. (See example with market we discussed: https://github.com/OpenFn/wcs-wildmeat/blob/master/jobs/2.c.market.js#L29-L35)

### expression.js
Jobs 2a, 2b, 2c, 2d

### state.json
Postgres DB: See LP `Wildmeat Postgres Transitional DB (WCS)`

**Comment by lakhassane** [comment]
I added the format for `findValue`.

@daissatou2 feel free to look here for inspiration in case you want to replicate: https://github.com/OpenFn/wcs-wildmeat/blob/master/jobs/2.c.market.js#L23-L39
